// AUTO-GENERATED by scripts/collect-repo-stats.mjs at build time.
// Committed as the fail-safe baseline; refreshed on every build (buildStart).
// Do not edit by hand.
import type { RepoStat } from "./repoStats";

export const repoStats: Record<string, RepoStat> = {
  "Aider-AI/aider": {
    "stars": 47304,
    "forks": 4722,
    "pushedAt": "2026-05-22T14:02:20Z",
    "fetchedAt": "2026-07-12"
  },
  "BerriAI/litellm": {
    "stars": 53290,
    "forks": 9675,
    "pushedAt": "2026-07-12T01:01:43Z",
    "fetchedAt": "2026-07-12"
  },
  "CherryHQ/cherry-studio": {
    "stars": 48452,
    "forks": 4602,
    "pushedAt": "2026-07-11T17:23:53Z",
    "fetchedAt": "2026-07-12"
  },
  "CopilotKit/CopilotKit": {
    "stars": 35924,
    "forks": 4435,
    "pushedAt": "2026-07-12T00:03:26Z",
    "fetchedAt": "2026-07-12"
  },
  "HKUDS/nanobot": {
    "stars": 45267,
    "forks": 7986,
    "pushedAt": "2026-07-11T16:35:17Z",
    "fetchedAt": "2026-07-12"
  },
  "NomaDamas/k-skill": {
    "stars": 6154,
    "forks": 699,
    "pushedAt": "2026-07-11T11:54:42Z",
    "fetchedAt": "2026-07-12"
  },
  "NousResearch/hermes-agent": {
    "stars": 213301,
    "forks": 39447,
    "pushedAt": "2026-07-11T18:16:13Z",
    "fetchedAt": "2026-07-12"
  },
  "OpenHands/OpenHands": {
    "stars": 80486,
    "forks": 10265,
    "pushedAt": "2026-07-11T21:26:07Z",
    "fetchedAt": "2026-07-12"
  },
  "RooCodeInc/Roo-Code": {
    "stars": 24321,
    "forks": 3363,
    "pushedAt": "2026-05-15T18:08:47Z",
    "fetchedAt": "2026-07-12"
  },
  "SWE-agent/SWE-agent": {
    "stars": 19777,
    "forks": 2163,
    "pushedAt": "2026-07-07T15:57:40Z",
    "fetchedAt": "2026-07-12"
  },
  "Significant-Gravitas/AutoGPT": {
    "stars": 185479,
    "forks": 46110,
    "pushedAt": "2026-07-11T20:00:23Z",
    "fetchedAt": "2026-07-12"
  },
  "Yeachan-Heo/gajae-code": {
    "stars": 1796,
    "forks": 266,
    "pushedAt": "2026-07-12T00:51:41Z",
    "fetchedAt": "2026-07-12"
  },
  "Yeachan-Heo/oh-my-claudecode": {
    "stars": 37676,
    "forks": 3402,
    "pushedAt": "2026-07-11T17:50:46Z",
    "fetchedAt": "2026-07-12"
  },
  "Yeachan-Heo/oh-my-codex": {
    "stars": 31915,
    "forks": 2467,
    "pushedAt": "2026-07-12T00:36:16Z",
    "fetchedAt": "2026-07-12"
  },
  "aaif-goose/goose": {
    "stars": 51092,
    "forks": 5678,
    "pushedAt": "2026-07-11T23:22:01Z",
    "fetchedAt": "2026-07-12"
  },
  "anomalyco/opencode": {
    "stars": 184840,
    "forks": 23067,
    "pushedAt": "2026-07-11T23:51:44Z",
    "fetchedAt": "2026-07-12"
  },
  "anthropics/claude-code": {
    "stars": 137461,
    "forks": 22201,
    "pushedAt": "2026-07-11T00:52:10Z",
    "fetchedAt": "2026-07-12"
  },
  "browser-use/browser-use": {
    "stars": 104275,
    "forks": 11495,
    "pushedAt": "2026-07-11T19:37:27Z",
    "fetchedAt": "2026-07-12"
  },
  "bytedance/deer-flow": {
    "stars": 76794,
    "forks": 10430,
    "pushedAt": "2026-07-12T01:00:13Z",
    "fetchedAt": "2026-07-12"
  },
  "cline/cline": {
    "stars": 64551,
    "forks": 6893,
    "pushedAt": "2026-07-11T08:00:34Z",
    "fetchedAt": "2026-07-12"
  },
  "code-yeongyu/lazycodex": {
    "stars": 2664,
    "forks": 169,
    "pushedAt": "2026-07-11T19:52:58Z",
    "fetchedAt": "2026-07-12"
  },
  "code-yeongyu/oh-my-openagent": {
    "stars": 65564,
    "forks": 5345,
    "pushedAt": "2026-07-11T19:53:01Z",
    "fetchedAt": "2026-07-12"
  },
  "crewAIInc/crewAI": {
    "stars": 55366,
    "forks": 7804,
    "pushedAt": "2026-07-11T22:26:03Z",
    "fetchedAt": "2026-07-12"
  },
  "danny-avila/LibreChat": {
    "stars": 40597,
    "forks": 8332,
    "pushedAt": "2026-07-11T21:42:45Z",
    "fetchedAt": "2026-07-12"
  },
  "devswha/patina": {
    "stars": 259,
    "forks": 28,
    "pushedAt": "2026-07-11T16:53:37Z",
    "fetchedAt": "2026-07-12"
  },
  "earendil-works/pi": {
    "stars": 69703,
    "forks": 8585,
    "pushedAt": "2026-07-11T13:20:09Z",
    "fetchedAt": "2026-07-12"
  },
  "facebook/react": {
    "stars": 246428,
    "forks": 51193,
    "pushedAt": "2026-07-10T03:04:54Z",
    "fetchedAt": "2026-07-12"
  },
  "firecrawl/firecrawl": {
    "stars": 149382,
    "forks": 8547,
    "pushedAt": "2026-07-11T23:09:42Z",
    "fetchedAt": "2026-07-12"
  },
  "google-gemini/gemini-cli": {
    "stars": 105926,
    "forks": 14247,
    "pushedAt": "2026-07-12T00:48:55Z",
    "fetchedAt": "2026-07-12"
  },
  "infiniflow/ragflow": {
    "stars": 84831,
    "forks": 9906,
    "pushedAt": "2026-07-11T15:38:22Z",
    "fetchedAt": "2026-07-12"
  },
  "langchain-ai/langchain": {
    "stars": 141551,
    "forks": 23530,
    "pushedAt": "2026-07-11T22:01:28Z",
    "fetchedAt": "2026-07-12"
  },
  "langgenius/dify": {
    "stars": 148522,
    "forks": 23414,
    "pushedAt": "2026-07-11T13:22:51Z",
    "fetchedAt": "2026-07-12"
  },
  "microsoft/autogen": {
    "stars": 59665,
    "forks": 8982,
    "pushedAt": "2026-04-15T11:59:09Z",
    "fetchedAt": "2026-07-12"
  },
  "ollama/ollama": {
    "stars": 175938,
    "forks": 16940,
    "pushedAt": "2026-07-10T00:42:15Z",
    "fetchedAt": "2026-07-12"
  },
  "omnigent-ai/omnigent": {
    "stars": 7088,
    "forks": 961,
    "pushedAt": "2026-07-11T13:13:00Z",
    "fetchedAt": "2026-07-12"
  },
  "open-webui/open-webui": {
    "stars": 145093,
    "forks": 21017,
    "pushedAt": "2026-07-10T23:32:22Z",
    "fetchedAt": "2026-07-12"
  },
  "openai/codex": {
    "stars": 97204,
    "forks": 14470,
    "pushedAt": "2026-07-11T21:05:32Z",
    "fetchedAt": "2026-07-12"
  },
  "openinterpreter/openinterpreter": {
    "stars": 64337,
    "forks": 5607,
    "pushedAt": "2026-07-07T00:59:25Z",
    "fetchedAt": "2026-07-12"
  },
  "unclecode/crawl4ai": {
    "stars": 72365,
    "forks": 7418,
    "pushedAt": "2026-07-11T08:24:39Z",
    "fetchedAt": "2026-07-12"
  },
  "vllm-project/vllm": {
    "stars": 85992,
    "forks": 19281,
    "pushedAt": "2026-07-12T00:13:51Z",
    "fetchedAt": "2026-07-12"
  }
};
