// AUTO-GENERATED by scripts/collect-repo-stats.mjs at build time.
// Committed as the fail-safe baseline; refreshed on every build (buildStart).
// Do not edit by hand.
import type { RepoStat } from "./repoStats";

export const repoStats: Record<string, RepoStat> = {
  "Aider-AI/aider": {
    "stars": 47142,
    "forks": 4706,
    "pushedAt": "2026-05-22T14:02:20Z",
    "fetchedAt": "2026-07-07"
  },
  "BerriAI/litellm": {
    "stars": 52844,
    "forks": 9536,
    "pushedAt": "2026-07-07T07:49:22Z",
    "fetchedAt": "2026-07-07"
  },
  "CherryHQ/cherry-studio": {
    "stars": 48260,
    "forks": 4586,
    "pushedAt": "2026-07-07T11:18:10Z",
    "fetchedAt": "2026-07-07"
  },
  "CopilotKit/CopilotKit": {
    "stars": 35816,
    "forks": 4438,
    "pushedAt": "2026-07-07T10:49:05Z",
    "fetchedAt": "2026-07-07"
  },
  "HKUDS/nanobot": {
    "stars": 45095,
    "forks": 7957,
    "pushedAt": "2026-07-07T10:45:00Z",
    "fetchedAt": "2026-07-07"
  },
  "NomaDamas/k-skill": {
    "stars": 6095,
    "forks": 688,
    "pushedAt": "2026-07-07T08:02:09Z",
    "fetchedAt": "2026-07-07"
  },
  "NousResearch/hermes-agent": {
    "stars": 210675,
    "forks": 38632,
    "pushedAt": "2026-07-07T11:13:49Z",
    "fetchedAt": "2026-07-07"
  },
  "OpenHands/OpenHands": {
    "stars": 79725,
    "forks": 10169,
    "pushedAt": "2026-07-07T11:00:08Z",
    "fetchedAt": "2026-07-07"
  },
  "RooCodeInc/Roo-Code": {
    "stars": 24311,
    "forks": 3355,
    "pushedAt": "2026-05-15T18:08:47Z",
    "fetchedAt": "2026-07-07"
  },
  "SWE-agent/SWE-agent": {
    "stars": 19721,
    "forks": 2154,
    "pushedAt": "2026-07-06T16:03:50Z",
    "fetchedAt": "2026-07-07"
  },
  "Significant-Gravitas/AutoGPT": {
    "stars": 185412,
    "forks": 46125,
    "pushedAt": "2026-07-07T10:57:53Z",
    "fetchedAt": "2026-07-07"
  },
  "Yeachan-Heo/gajae-code": {
    "stars": 1670,
    "forks": 241,
    "pushedAt": "2026-07-07T11:16:11Z",
    "fetchedAt": "2026-07-07"
  },
  "Yeachan-Heo/oh-my-claudecode": {
    "stars": 37506,
    "forks": 3379,
    "pushedAt": "2026-07-07T11:15:45Z",
    "fetchedAt": "2026-07-07"
  },
  "Yeachan-Heo/oh-my-codex": {
    "stars": 31755,
    "forks": 2462,
    "pushedAt": "2026-07-07T05:17:44Z",
    "fetchedAt": "2026-07-07"
  },
  "aaif-goose/goose": {
    "stars": 50765,
    "forks": 5467,
    "pushedAt": "2026-07-07T03:36:00Z",
    "fetchedAt": "2026-07-07"
  },
  "anomalyco/opencode": {
    "stars": 183221,
    "forks": 22716,
    "pushedAt": "2026-07-07T09:17:56Z",
    "fetchedAt": "2026-07-07"
  },
  "anthropics/claude-code": {
    "stars": 136640,
    "forks": 21955,
    "pushedAt": "2026-07-06T22:51:16Z",
    "fetchedAt": "2026-07-07"
  },
  "browser-use/browser-use": {
    "stars": 103254,
    "forks": 11426,
    "pushedAt": "2026-07-07T02:59:23Z",
    "fetchedAt": "2026-07-07"
  },
  "bytedance/deer-flow": {
    "stars": 76332,
    "forks": 10353,
    "pushedAt": "2026-07-07T06:39:04Z",
    "fetchedAt": "2026-07-07"
  },
  "cline/cline": {
    "stars": 64393,
    "forks": 6859,
    "pushedAt": "2026-07-07T07:15:53Z",
    "fetchedAt": "2026-07-07"
  },
  "code-yeongyu/lazycodex": {
    "stars": 2518,
    "forks": 161,
    "pushedAt": "2026-07-03T12:15:12Z",
    "fetchedAt": "2026-07-07"
  },
  "code-yeongyu/oh-my-openagent": {
    "stars": 65131,
    "forks": 5317,
    "pushedAt": "2026-07-07T07:37:32Z",
    "fetchedAt": "2026-07-07"
  },
  "crewAIInc/crewAI": {
    "stars": 55063,
    "forks": 7736,
    "pushedAt": "2026-07-07T07:35:10Z",
    "fetchedAt": "2026-07-07"
  },
  "danny-avila/LibreChat": {
    "stars": 40386,
    "forks": 8276,
    "pushedAt": "2026-07-07T11:15:28Z",
    "fetchedAt": "2026-07-07"
  },
  "devswha/patina": {
    "stars": 240,
    "forks": 26,
    "pushedAt": "2026-07-07T11:08:21Z",
    "fetchedAt": "2026-07-07"
  },
  "earendil-works/pi": {
    "stars": 68305,
    "forks": 8393,
    "pushedAt": "2026-07-07T05:14:39Z",
    "fetchedAt": "2026-07-07"
  },
  "facebook/react": {
    "stars": 246261,
    "forks": 51232,
    "pushedAt": "2026-07-07T05:31:01Z",
    "fetchedAt": "2026-07-07"
  },
  "firecrawl/firecrawl": {
    "stars": 146899,
    "forks": 8444,
    "pushedAt": "2026-07-07T09:55:03Z",
    "fetchedAt": "2026-07-07"
  },
  "google-gemini/gemini-cli": {
    "stars": 105822,
    "forks": 14230,
    "pushedAt": "2026-07-07T01:56:36Z",
    "fetchedAt": "2026-07-07"
  },
  "infiniflow/ragflow": {
    "stars": 84494,
    "forks": 9843,
    "pushedAt": "2026-07-07T11:06:30Z",
    "fetchedAt": "2026-07-07"
  },
  "langchain-ai/langchain": {
    "stars": 141176,
    "forks": 23465,
    "pushedAt": "2026-07-07T09:07:01Z",
    "fetchedAt": "2026-07-07"
  },
  "langgenius/dify": {
    "stars": 148017,
    "forks": 23316,
    "pushedAt": "2026-07-07T11:17:03Z",
    "fetchedAt": "2026-07-07"
  },
  "microsoft/autogen": {
    "stars": 59548,
    "forks": 8963,
    "pushedAt": "2026-04-15T11:59:09Z",
    "fetchedAt": "2026-07-07"
  },
  "ollama/ollama": {
    "stars": 175639,
    "forks": 16869,
    "pushedAt": "2026-07-07T01:11:57Z",
    "fetchedAt": "2026-07-07"
  },
  "omnigent-ai/omnigent": {
    "stars": 6523,
    "forks": 866,
    "pushedAt": "2026-07-07T11:04:30Z",
    "fetchedAt": "2026-07-07"
  },
  "open-webui/open-webui": {
    "stars": 144535,
    "forks": 20889,
    "pushedAt": "2026-07-02T17:38:23Z",
    "fetchedAt": "2026-07-07"
  },
  "openai/codex": {
    "stars": 96006,
    "forks": 14247,
    "pushedAt": "2026-07-07T11:07:14Z",
    "fetchedAt": "2026-07-07"
  },
  "openinterpreter/openinterpreter": {
    "stars": 64295,
    "forks": 5595,
    "pushedAt": "2026-07-07T00:59:25Z",
    "fetchedAt": "2026-07-07"
  },
  "unclecode/crawl4ai": {
    "stars": 71255,
    "forks": 7326,
    "pushedAt": "2026-07-07T08:24:02Z",
    "fetchedAt": "2026-07-07"
  },
  "vllm-project/vllm": {
    "stars": 85585,
    "forks": 19062,
    "pushedAt": "2026-07-07T10:51:18Z",
    "fetchedAt": "2026-07-07"
  }
};
