// AUTO-GENERATED by scripts/collect-repo-stats.mjs at build time.
// Committed as the fail-safe baseline; refreshed on every build (buildStart).
// Do not edit by hand.
import type { RepoStat } from "./repoStats";

export const repoStats: Record<string, RepoStat> = {
  "Aider-AI/aider": {
    "stars": 47260,
    "forks": 4717,
    "pushedAt": "2026-05-22T14:02:20Z",
    "fetchedAt": "2026-07-11"
  },
  "BerriAI/litellm": {
    "stars": 53226,
    "forks": 9651,
    "pushedAt": "2026-07-11T01:02:06Z",
    "fetchedAt": "2026-07-11"
  },
  "CherryHQ/cherry-studio": {
    "stars": 48418,
    "forks": 4598,
    "pushedAt": "2026-07-11T01:00:17Z",
    "fetchedAt": "2026-07-11"
  },
  "CopilotKit/CopilotKit": {
    "stars": 35910,
    "forks": 4438,
    "pushedAt": "2026-07-11T00:47:09Z",
    "fetchedAt": "2026-07-11"
  },
  "HKUDS/nanobot": {
    "stars": 45225,
    "forks": 7986,
    "pushedAt": "2026-07-10T17:14:52Z",
    "fetchedAt": "2026-07-11"
  },
  "NomaDamas/k-skill": {
    "stars": 6148,
    "forks": 695,
    "pushedAt": "2026-07-10T17:10:53Z",
    "fetchedAt": "2026-07-11"
  },
  "NousResearch/hermes-agent": {
    "stars": 212772,
    "forks": 39282,
    "pushedAt": "2026-07-11T00:07:35Z",
    "fetchedAt": "2026-07-11"
  },
  "OpenHands/OpenHands": {
    "stars": 80380,
    "forks": 10255,
    "pushedAt": "2026-07-10T23:37:20Z",
    "fetchedAt": "2026-07-11"
  },
  "RooCodeInc/Roo-Code": {
    "stars": 24317,
    "forks": 3363,
    "pushedAt": "2026-05-15T18:08:47Z",
    "fetchedAt": "2026-07-11"
  },
  "SWE-agent/SWE-agent": {
    "stars": 19762,
    "forks": 2159,
    "pushedAt": "2026-07-07T15:57:40Z",
    "fetchedAt": "2026-07-11"
  },
  "Significant-Gravitas/AutoGPT": {
    "stars": 185454,
    "forks": 46114,
    "pushedAt": "2026-07-11T00:54:34Z",
    "fetchedAt": "2026-07-11"
  },
  "Yeachan-Heo/gajae-code": {
    "stars": 1766,
    "forks": 263,
    "pushedAt": "2026-07-11T00:41:05Z",
    "fetchedAt": "2026-07-11"
  },
  "Yeachan-Heo/oh-my-claudecode": {
    "stars": 37649,
    "forks": 3399,
    "pushedAt": "2026-07-10T17:21:43Z",
    "fetchedAt": "2026-07-11"
  },
  "Yeachan-Heo/oh-my-codex": {
    "stars": 31897,
    "forks": 2466,
    "pushedAt": "2026-07-10T23:44:01Z",
    "fetchedAt": "2026-07-11"
  },
  "aaif-goose/goose": {
    "stars": 51044,
    "forks": 5652,
    "pushedAt": "2026-07-11T00:53:18Z",
    "fetchedAt": "2026-07-11"
  },
  "anomalyco/opencode": {
    "stars": 184561,
    "forks": 23006,
    "pushedAt": "2026-07-11T01:02:03Z",
    "fetchedAt": "2026-07-11"
  },
  "anthropics/claude-code": {
    "stars": 137317,
    "forks": 22167,
    "pushedAt": "2026-07-11T00:52:10Z",
    "fetchedAt": "2026-07-11"
  },
  "browser-use/browser-use": {
    "stars": 104138,
    "forks": 11482,
    "pushedAt": "2026-07-11T00:47:15Z",
    "fetchedAt": "2026-07-11"
  },
  "bytedance/deer-flow": {
    "stars": 76736,
    "forks": 10417,
    "pushedAt": "2026-07-11T00:54:46Z",
    "fetchedAt": "2026-07-11"
  },
  "cline/cline": {
    "stars": 64531,
    "forks": 6888,
    "pushedAt": "2026-07-11T00:41:57Z",
    "fetchedAt": "2026-07-11"
  },
  "code-yeongyu/lazycodex": {
    "stars": 2631,
    "forks": 170,
    "pushedAt": "2026-07-10T14:06:12Z",
    "fetchedAt": "2026-07-11"
  },
  "code-yeongyu/oh-my-openagent": {
    "stars": 65501,
    "forks": 5343,
    "pushedAt": "2026-07-10T22:09:56Z",
    "fetchedAt": "2026-07-11"
  },
  "crewAIInc/crewAI": {
    "stars": 55316,
    "forks": 7789,
    "pushedAt": "2026-07-11T00:37:38Z",
    "fetchedAt": "2026-07-11"
  },
  "danny-avila/LibreChat": {
    "stars": 40560,
    "forks": 8329,
    "pushedAt": "2026-07-10T19:47:30Z",
    "fetchedAt": "2026-07-11"
  },
  "devswha/patina": {
    "stars": 257,
    "forks": 28,
    "pushedAt": "2026-07-10T14:53:42Z",
    "fetchedAt": "2026-07-11"
  },
  "earendil-works/pi": {
    "stars": 69500,
    "forks": 8539,
    "pushedAt": "2026-07-10T22:01:49Z",
    "fetchedAt": "2026-07-11"
  },
  "facebook/react": {
    "stars": 246377,
    "forks": 51168,
    "pushedAt": "2026-07-10T03:04:54Z",
    "fetchedAt": "2026-07-11"
  },
  "firecrawl/firecrawl": {
    "stars": 148927,
    "forks": 8513,
    "pushedAt": "2026-07-10T23:44:18Z",
    "fetchedAt": "2026-07-11"
  },
  "google-gemini/gemini-cli": {
    "stars": 105900,
    "forks": 14236,
    "pushedAt": "2026-07-10T17:23:27Z",
    "fetchedAt": "2026-07-11"
  },
  "infiniflow/ragflow": {
    "stars": 84778,
    "forks": 9898,
    "pushedAt": "2026-07-10T15:24:04Z",
    "fetchedAt": "2026-07-11"
  },
  "langchain-ai/langchain": {
    "stars": 141484,
    "forks": 23509,
    "pushedAt": "2026-07-10T23:06:20Z",
    "fetchedAt": "2026-07-11"
  },
  "langgenius/dify": {
    "stars": 148438,
    "forks": 23397,
    "pushedAt": "2026-07-10T22:12:52Z",
    "fetchedAt": "2026-07-11"
  },
  "microsoft/autogen": {
    "stars": 59645,
    "forks": 8978,
    "pushedAt": "2026-04-15T11:59:09Z",
    "fetchedAt": "2026-07-11"
  },
  "ollama/ollama": {
    "stars": 175892,
    "forks": 16923,
    "pushedAt": "2026-07-10T00:42:15Z",
    "fetchedAt": "2026-07-11"
  },
  "omnigent-ai/omnigent": {
    "stars": 7008,
    "forks": 945,
    "pushedAt": "2026-07-10T23:50:11Z",
    "fetchedAt": "2026-07-11"
  },
  "open-webui/open-webui": {
    "stars": 145000,
    "forks": 20994,
    "pushedAt": "2026-07-10T23:32:22Z",
    "fetchedAt": "2026-07-11"
  },
  "openai/codex": {
    "stars": 97009,
    "forks": 14409,
    "pushedAt": "2026-07-11T00:12:10Z",
    "fetchedAt": "2026-07-11"
  },
  "openinterpreter/openinterpreter": {
    "stars": 64332,
    "forks": 5606,
    "pushedAt": "2026-07-07T00:59:25Z",
    "fetchedAt": "2026-07-11"
  },
  "unclecode/crawl4ai": {
    "stars": 72239,
    "forks": 7403,
    "pushedAt": "2026-07-09T14:46:56Z",
    "fetchedAt": "2026-07-11"
  },
  "vllm-project/vllm": {
    "stars": 85931,
    "forks": 19250,
    "pushedAt": "2026-07-11T00:16:50Z",
    "fetchedAt": "2026-07-11"
  }
};
